name: Lint, format and test code
on:
  workflow_dispatch:
  pull_request:
    paths:
      - terragrunt/aws/cloud_asset_inventory/src/**
      - .github/workflows/ci_code.yml

jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          make install
          make install-dev

      - name: Lint
        run: make lint-ci

      - name: Format
        run: make fmt-ci

      - name: Test
        run: make test
